name: Deploy Databricks Bundle
on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
        description: "Target environment (development/production)"
      repo_owner:
        required: true
        type: string
        description: "Owner of the repository containing the bundle"
      repo_name:
        required: true
        type: string
        description: "Name of the repository containing the bundle"
    secrets:
      REPO_READ_TOKEN:
        required: true
        description: "PAT token to read the bundle repository"
      DATABRICKS_HOST:
        required: true
        description: "Databricks workspace host URL"
      DATABRICKS_TOKEN:
        required: true
        description: "Databricks authentication token"
  
  repository_dispatch:
    types: [deploy_desarrollo, deploy_produccion]

env:
  REPO_OWNER_IN: ${{ inputs.repo_owner || github.event.client_payload.repo_owner || 'benjaminvergara19' }}
  REPO_NAME_IN: ${{ inputs.repo_name || github.event.client_payload.repo_name || 'poc_publico_bvi' }}
  TARGET_ENV: ${{ inputs.target_env || github.event.client_payload.target_env || 'development' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código del proyecto
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_OWNER_IN }}/${{ env.REPO_NAME_IN }}
          token: ${{ secrets.REPO_READ_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          echo "/github/home/.databricks/bin" >> $GITHUB_PATH
          
      - name: Show Bundle Configuration
        run: |
          echo "=== Bundle Configuration ==="
          cat databricks.yml
          echo ""
          echo "=== Resource Files ==="
          find resources -name "*.yml" -exec echo "File: {}" \; -exec cat {} \; -exec echo "" \;
        
      - name: Validate Bundle
        run: databricks bundle validate --target "${TARGET_ENV}"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        
      - name: Deploy Bundle
        run: databricks bundle deploy --target "${TARGET_ENV}" --verbose
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        
      - name: List Created Jobs
        run: |
          echo "=== Listing all jobs ==="
          databricks jobs list
          echo ""
          echo "=== Searching for Poc jobs ==="
          databricks jobs list | grep -i "poc" || echo "No jobs found with 'poc' in name"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          
      - name: List Workspace Bundle
        run: |
          echo "=== Bundle workspace contents ==="
          databricks workspace list /Users/benjamin.vergara@uc.cl/.bundle/Poc/development/ || echo "Bundle path not found"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}